include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - functions/node_modules/**
    - node_modules/**
    - web/magnetic-tree/node_modules/**

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
